steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}'
      ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - ${_VM_NAME}
      - --zone=${_ZONE}
      - --command=sudo docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME} && sudo docker stop flask-web-app || true && sudo docker rm flask-web-app || true && sudo docker run -d --name flask-web-app -p 80:5000 ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}

substitutions:
  _REGION: us-central1
  _REPOSITORY: devops-repo
  _IMAGE_NAME: flask-web-app
  _VM_NAME: haks-test-01
  _ZONE: us-central1-c

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}'
